project_id = "rvqocmnfaowcfuvznfwn"

[functions.ingest-receiver]
verify_jwt = false

[functions.document-processor]
verify_jwt = false

[functions.video-processor]
verify_jwt = false

[functions.pipeline-orchestrator]
verify_jwt = false

[functions.rss-ingester]
verify_jwt = false

[functions.live-data-ingester]
verify_jwt = false
